Нужно больше функций
htmlacademy-javascript/2249147-kekstagram-28 pull request #2
Opened 2023-02-22 20:10 UTC by dmitrii-kulganek

2023-02-26 15:04 UTC, yurylavrukhin requested changes
закинул небольшие изменения 🤗  отличный старт! 🚀

2023-02-26 15:04 UTC, yurylavrukhin commented on js/functions.js
> +  }
👍

2023-02-28 18:08 UTC, dmitrii-kulganek commented on js/functions.js
> +const isLenghtString = (testString, amountCharacters) => testString.length <= amountCharacters;
Думал о названии типа isLenghtStringMoreThan, но побоялся слишком длинного названия.
Твой вариант лаконичнее))) Изменил.

2023-02-28 18:12 UTC, dmitrii-kulganek commented on js/functions.js
> +  testString = testString
Понял. Точно! Реально понятнее! ))) Изменил.

2023-02-28 18:22 UTC, dmitrii-kulganek commented on js/functions.js
> +  }
Про массивы я чуть позже узнал, что можно так сделать.
А т.к. массивы условно ещё не знал, как применять, писал только на основании пройденного материала.

Всё же поправил на массивы, так сильно короче )))

2023-03-01 02:59 UTC, yurylavrukhin commented on js/functions.js
> +    numbers = !isNaN(parseInt(testString[i], 10)) ? numbers + testString[i] : numbers; //Проверка, является ли символ числом через приведение символа строки к числу и проверка на NaN
> Т.к. я использую уже точно число, то корректнее проверять именно число на NaN?

да

2023-03-01 02:59 UTC, yurylavrukhin approved these changes
Кайфы! 🚀

2023-03-01 03:00 UTC, merged